apiVersion: v1
kind: Namespace
metadata:
  name: project

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project
  namespace: project
  labels:
    app: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
        - name: the-project
          image: the_project
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: image-cache
              mountPath: /data
          env:
            - name: IMAGE_PATH
              value: /data/image.jpg
            - name: TIMESTAMP_PATH
              value: /data/last_fetched.txt
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: the-project-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: the-project-pvc
  namespace: project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
