apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
        - name: the-project
          image: the_project:local
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: image-cache
              mountPath: /data
          env:
            - name: IMAGE_PATH
              value: /data/image.jpg
            - name: TIMESTAMP_PATH
              value: /data/last_fetched.txt
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: the-project-pvc
