apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theproject
  template:
    metadata:
      labels:
        app: theproject
    spec:
      containers:
        - name: theproject
          image: the-project:local
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
