apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project
  labels:
    app: the-project
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
        - name: the-project
          image: the_project
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: image-cache
              mountPath: /data
          env:
            - name: IMAGE_PATH
              value: /data/image.jpg
            - name: TIMESTAMP_PATH
              value: /data/last_fetched.txt
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: the-project-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: the-project-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
