apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: the_project
    newName: gcr.io/k8s-course-466712/the_project
    newTag: gcr
