apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: the_project
  newName: europe-central2-docker.pkg.dev/k8s-course-466712/course-repo/the_project
  newTag: e9fbef68aceae133cc74761bc2de7f8db1eebaac
