apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: the-project-pvc
  namespace: project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
