apiVersion: v1
kind: Service
metadata:
  name: the-project-svc
spec:
  type: ClusterIP
  selector:
    app: the-project # app that declared in deployment
  ports:
    - protocol: TCP
      port: 1234 # cluster-internal port, it can be ~ anything (used for internal comm)
      targetPort: 3000 # This is the target port (inside the pod)
