apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-site-controller
  labels:
    app: dummy-site-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-site-controller
  template:
    metadata:
      labels:
        app: dummy-site-controller
    spec:
      serviceAccountName: dummy-site-controller
      containers:
        - name: controller
          image: dummy-controller:local
          imagePullPolicy: Never
