# greeter-v1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v1
  template:
    metadata:
      labels:
        app: greeter
        version: v1
    spec:
      containers:
        - name: greeter
          image: europe-central2-docker.pkg.dev/k8s-course-466712/course-repo/greeter:ar
          env:
            - name: VERSION
              value: "v1"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: greeter-svc-v1
spec:
  selector:
    app: greeter
    version: v1
  ports:
    - port: 80
      targetPort: 8080
