apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: greeter-route
spec:
  parentRefs:
    - name: greeter-svc
      kind: Service
  rules:
    - backendRefs:
        - name: greeter-svc-v1
          weight: 75
        - name: greeter-svc-v2
          weight: 25
