apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-wiki-todo
  namespace: project
spec:
  schedule: "0 * * * *"  # every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wiki-todo
              image: todo_backend:local
              command: ["node", "random-todo.js"]
          restartPolicy: OnFailure
