apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  labels:
    app: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: todo_backend
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              value: "postgres"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-wiki-todo
spec:
  schedule: "0 * * * *" # every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wiki-todo
              image: todo_backend:local
              command: ["node", "random-todo.js"]
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 0 * * *" # once every 24h at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pg-backup
              image: google/cloud-sdk:slim
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: POSTGRES_PASSWORD
              volumeMounts:
                - name: gcs-key
                  mountPath: /secrets
                  readOnly: true
              command:
                - /bin/bash
                - -c
                - |
                  apt-get update && apt-get install -y postgresql-client
                  pg_dump -h postgres -U user -d todosdb > backup.sql
                  gcloud auth activate-service-account --key-file=/secrets/key.json
                  gsutil cp backup.sql gs://todo-db-backup/backup-$(date +%F).sql
          restartPolicy: OnFailure
          volumes:
            - name: gcs-key
              secret:
                secretName: gcs-key
