apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - postgres.yaml

images:
  - name: todo_backend
    newName: europe-central2-docker.pkg.dev/k8s-course-466712/course-repo/todo_backend
    newTag: ar
