apiVersion: v1
kind: Pod
metadata:
  name: wiki-app
spec:
  volumes:
    - name: www-data
      emptyDir: {}
  initContainers:
    - name: init-fetch
      image: curlimages/curl
      command:
        [
          "sh",
          "-c",
          "curl -s https://en.wikipedia.org/wiki/Kubernetes -o /usr/share/nginx/html/kubernetes.html",
        ]
      volumeMounts:
        - name: www-data
          mountPath: /usr/share/nginx/html
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - name: www-data
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /kubernetes.html
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10

    - name: sidecar
      image: wiki-sidecar:local
      volumeMounts:
        - name: www-data
          mountPath: /usr/share/nginx/html
