apiVersion: v1
kind: Namespace
metadata:
  name: exercises

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: gcr.io/k8s-course-466712/ping_pong:gcr
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: user
            - name: PGPASSWORD
              value: password
            - name: PGDATABASE
              value: pingpongdb
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: ping-pong
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
