apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-output
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/OzturkVedat/KubernetesSubmissions"
    targetRevision: main
    path: log_output/manifests # check whether smt changed here (e.g. image tag)
  destination:
    server: https://kubernetes.default.svc
    namespace: exercises
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
