apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: writer
          image: log_output:local
          command: ["node", "writer.js"]

        - name: reader
          image: log_output:local
          command: ["node", "reader.js"]
          ports:
            - containerPort: 3000
          env:
            - name: PING_PONG_HOST
              value: "ping-pong-svc"
            - name: PING_PONG_PORT
              value: "1235"  
