apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}     
      containers:
        - name: writer
          image: log_output:local
          command: ["node", "writer.js"]
          volumeMounts:
            - name: shared-logs
              mountPath: /shared

        - name: reader
          image: log_output:local
          command: ["node", "reader.js"]
          ports:
          - containerPort: 3000  
          volumeMounts:
            - name: shared-logs
              mountPath: /shared