apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml

images:
- name: log_output
  newName: europe-central2-docker.pkg.dev/k8s-course-466712/course-repo/log_output
  newTag: 95ed82edf85f6d87d640d7681e132675cb9d6b0c
