name: Delete Cluster Namespace

on:
  workflow_dispatch:

env:
  CLUSTER_NAME: course-cluster
  CLUSTER_ZONE: europe-central2-a
  PROJECT_ID: k8s-course-466712

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Set Namespace from Branch
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "NAMESPACE=project" >> $GITHUB_ENV
          else
            echo "NAMESPACE=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: Auth to GCloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_ZONE }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Delete namespace if it exists
        run: |
          if kubectl get namespace $NAMESPACE &> /dev/null; then
            echo "Deleting namespace: $NAMESPACE"
            kubectl delete namespace $NAMESPACE
          else
            echo "Namespace $NAMESPACE does not exist"
          fi
